### ISSUE TITLE
Should I be able to import any Node package with this?

### ISSUE THREAD

**Issue by stevenroose** [cedx/nodejs-interop.dart#2]
I'm trying to use this JS package: https://github.com/mohsen1/json-formatter-js

I tried several methods and all have failed so far: `dart:js`, `package:js`, `package:node_interop` and then this one.

Any idea how to use a generic JS library with Dart?

**Comment by cedx** [comment]
`dart:js` and `package:js` don't work with CommonJS modules.
`package:node_interop` and `package:nodejs_interop` don't work with browser modules.

The author uses TypeScript and Webpack to generate the final bundle (look at the file `dist/json-formatter.js` when you install the library using `npm install`).

The problem is that this bundle is still a CommonJS module : it is **NOT usable in a browser without a build step**.

For example, this code does not work at all (the browser console displays : `Uncaught SyntaxError: The requested module does not provide an export named 'default'`):

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
  </head>

  <body>
    <script type="module">
      import JSONFormatter from './node_modules/json-formatter-js/dist/json-formatter.js'
      const myJSON = {ans: 42};
      const formatter = new JSONFormatter(myJSON);
      document.body.appendChild(formatter.render());
    </script>
  </body>
</html>
```

So the `json-formatter-js` is simply not usable at all with Dart in its current state :( You should open an issue on the original project and ask the author to produce a plain browser module (i.e. without any Webpack or Node.js artifact like `require` calls or `module.exports` statements).
